{% set name = "fluidfft-fftw" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fluidfft_fftw-{{ version }}.tar.gz
  sha256: 59967846e1d976508db30ff65987e9c1e6c024ec9c095849608ee8913b96d3ff

build:
  number: 3
  skip: true  # [py<39 or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - python-build
    - pip
    - meson-python
    - numpy
    - fluidfft-builder >=0.0.1
    - cython
    - transonic >=0.6.1
    - fftw
  run:
    - python
    - fluidfft
    - fftw

test:
  imports:
    - fluidfft_fftw
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Fluidfft plugin using fftw
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://foss.heptapod.net/fluiddyn/fluidfft

extra:
  recipe-maintainers:
    - paugier
